export { CustomerCategoriesPage } from './CustomerCategoriesPage'
export { CustomerPaymentPage } from './CustomerPaymentPage'
export { CustomerSuccessPage } from './CustomerSuccessPage'
export { CustomerNotificationsPage } from './CustomerNotificationsPage'
export { CustomerOffersPage } from './CustomerOffersPage'
